### ISSUE TITLE
Not found?

### ISSUE THREAD

**Issue by peteruithoven** [pascalopitz/sonos-controller-for-chrome#3]
The documented chome store url doesn't seem to work anymore? 

![screenshot from 2016-11-03 11 48 34](https://cloud.githubusercontent.com/assets/523210/19963168/7ceb107e-a1bb-11e6-8447-55e01be87048.png)

**Comment by pascalopitz** [comment]
Yes, I pulled the app from chrome store. Two reasons: Too many bug reports and bad reviews due to factors I couldn't replicate, most seemed chromebook specific, and the looming removal of chrome apps from the chrome browser. I am working on an electron port.

**Comment by peteruithoven** [comment]
Awesome that you're working on an Electron App, that sounds like an even better solution. I'll check it out.

**Comment by pascalopitz** [comment]
Electron app now off the ground. Mind giving it a try? First Deb file here: http://pascalopitz.github.io/unoffical-sonos-controller-for-linux/dist/sonos-controller-unofficial-latest-amd64.deb

**Comment by leanto** [comment]
Do you have a raspberry pi .armhf version? If not, I can try building it myself if you give me a pointer.

**Comment by pascalopitz** [comment]
Sadly I don't think electron-builder supports that. You could try and check the project out in git and run it in develop mode to see if it would be working?

**Comment by peteruithoven** [comment]
Awesome! That installed very easily on Elementary OS Freya (based on Ubuntu 14 LTS). 
I see there are some issues, but great start!

**Comment by pascalopitz** [comment]
Great. Please keep opening issues if you find them and/or have suggestions for improvement.
I also will set up a ppa once I figure out how to, and everyone should get the updates via apt.

**Comment by peteruithoven** [comment]
You could also look into snaps, that could make it available for more Linux distros and make the install experience better. 

http://snapcraft.io/
https://www.youtube.com/watch?v=j40tNL3t4gw
http://www.linuxuk.org/post/20160518_snapping_electron_based_applications_simplenote/
https://github.com/electron-userland/electron-packager/issues/525
